prop_classes = [
    '',
    '3',
    '10 Miscellaneous Residential',
    '20 Miscellaneous Commercial',
    '30 Miscellaneous Industrial',
    '40 Miscellaneous Tract',
    '70 Miscellaneous Multifamily',
    '100 Residential Vacant',
    '101 Residential Improved',
    '102 Residential Condominium',
    '106 Residential Improved Waterfront',
    '109 Residential Improved Manufactured Structure',
    '121 Residential Commercial Zoned Improved',
    '131 Residential Industrial Zoned Improved',
    '139 Residential Industrial Zoned Manufactured Structure',
    '190 Residential Potential Development Vacant',
    '191 Residential Potential Development Improved',
    '196 Residential Waterfront Vacant',
    '199 Residential Potential Development Manufactured Structure',
    '200 Commercial Vacant',
    '201 Commercial Improved',
    '202 Commercial Condominium',
    '203',
    '210 Commercial Residential Zoned Vacant',
    '211 Commercial Residential Zoned Improved',
    '216 Commercial Residential Zoned Waterfront',
    '230 Commercial Industrial Zoned Vacant',
    '231 Commercial Industrial Zoned Improved',
    '241 Commercial Farm Deferred Unzoned Improved',
    '300 Industrial Vacant',
    '301 Industrial Improved',
    '303',
    '309 Industrial Manufactured Structure',
    '311 Industrial Residential Zoned Improved',
    '321 Industrial Commercial Zoned Improved',
    '340 Industrial Farm Deferral Vacant',
    '341 Industrial Farm Deferral Improved',
    '400 Tract Vacant',
    '401 Tract Improved',
    '406 Tract Improved Waterfront',
    '409 Tract Improved Manufactured Structure',
    '421 Tract Commercial Zoned Improved',
    '540 Farm Deferred Unzoned Vacant',
    '541 Farm Deferred Unzoned Improved',
    '549 Farm Deferred Unzoned Manufactured Structure',
    '550 Zoned Farm Vacant',
    '551 Zoned Farm Improved',
    '559 Zoned Farm Manufactured Structure',
    '640 Designated Forestland Vacant',
    '641 Designated Forestland Improved',
    '649 Designated Forestland Improved Manufactured Structure',
    '681 Designated Forestland Multiple Special Assessment Improved',
    '700 Multifamily Vacant',
    '701 Multifamily Improved',
    '707 Manufacture Structure Park',
    '711 Multifamily Residential Zoned Improved',
    '717 Manufactured Structure Park Residential Zoned',
    '721 Multifamily Commercial Zoned Improved',
    '727 Manufactured Structure Park Commercial Zoned',
    '737 Manufactured Structure Park Industrial Zoned',
    '781 Multifamily Special Assessment Improved'
]

residential = [
    '10 Miscellaneous Residential',
    '70 Miscellaneous Multifamily',
    '100 Residential Vacant',
    '101 Residential Improved',
    '102 Residential Condominium',
    '106 Residential Improved Waterfront',
    '109 Residential Improved Manufactured Structure',
    '121 Residential Commercial Zoned Improved',
    '131 Residential Industrial Zoned Improved',
    '139 Residential Industrial Zoned Manufactured Structure',
    '190 Residential Potential Development Vacant',
    '191 Residential Potential Development Improved',
    '196 Residential Waterfront Vacant',
    '199 Residential Potential Development Manufactured Structure',
    '202 Commercial Condominium',
    '210 Commercial Residential Zoned Vacant',
    '211 Commercial Residential Zoned Improved',
    '216 Commercial Residential Zoned Waterfront',
    '311 Industrial Residential Zoned Improved',
    '700 Multifamily Vacant',
    '701 Multifamily Improved',
    '711 Multifamily Residential Zoned Improved',
    '717 Manufactured Structure Park Residential Zoned',
    '721 Multifamily Commercial Zoned Improved',
    '781 Multifamily Special Assessment Improved',
]

apartments = [
    '70 Miscellaneous Multifamily',
    '102 Residential Condominium',
    '202 Commercial Condominium',
    '210 Commercial Residential Zoned Vacant',
    '211 Commercial Residential Zoned Improved',
    '216 Commercial Residential Zoned Waterfront',
    '311 Industrial Residential Zoned Improved',
    '700 Multifamily Vacant',
    '701 Multifamily Improved',
    '711 Multifamily Residential Zoned Improved',
    '717 Manufactured Structure Park Residential Zoned',
    '721 Multifamily Commercial Zoned Improved',
    '781 Multifamily Special Assessment Improved',
]
